version: '3'

services:
  admin:
    container_name: pgn-admin
    build: 
     context: ..   
     dockerfile: .devcontainer/Dockerfile

    command: flask run -p 6012 --host=0.0.0.0  
    #command: gunicorn -c gunicorn_config.py application
    environment:
        - PORT=6012
    ports: 
      - "6012:6012"

