on: push
name: Continuous Integration Testing
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image:  python:3.6-stretch
    steps:
    - uses: actions/checkout@v1     
    - run: /bin/bash -c "pip3 install -r requirements_for_test.txt && make test"